disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- function_body_length
- weak_delegate
- large_tuple
- todo
- unused_setter_value

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

file_length:
- 1000 # warning
- 1001 # error

type_body_length:
- 200 # warning
- 201 # error

line_length:
- 200 # warning
- 201 # error

cyclomatic_complexity:
- 10 # warning
- 11 # error
