disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- function_body_length
- weak_delegate
- large_tuple
- todo

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- Pods
- Project/R.generated.swift
- Main App/SwipeableTabBarController

file_length:
- 1999 # warning
- 2000 # error

type_body_length:
- 700 # warning
- 1000 # error

line_length:
- 400 # warning
- 500 # error

cyclomatic_complexity:
- 17 # warning
- 20 # error
