disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- function_body_length
- weak_delegate
- large_tuple
- todo
- unused_setter_value

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

file_length:
- 1500 # warning
- 1501 # error

type_body_length:
- 250 # warning
- 251 # error

line_length:
- 250 # warning
- 251 # error

cyclomatic_complexity:
- 16 # warning
- 17 # error
