disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- todo
- inert_defer
- syntactic_sugar
- implicit_getter
- non_optional_string_data_conversion
- private_over_fileprivate
- legacy_hashing
- redundant_discardable_let
- unneeded_break_in_switch
- empty_count

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 199 # warning
- 200 #error

file_length:
- 1999 # warning
- 2000 # error

type_body_length:
- 399 # warning
- 400 # error

line_length:
- 299 # warning
- 300 # error

cyclomatic_complexity:
- 19 # warning
- 20 # error

excluded:
- Pods
- Carthage
- .build
- Tests
